name: google_place_api
description: A new Flutter package for handle google place api that place search and details and photos and autocomplete and query autocomplete requests are available, forked from https://github.com/bazrafkan
version: 1.1.0
homepage: https://github.com/abdelrahman-atef1/google_place_api

environment:
  sdk: ^3.11.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^5.0.0
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
